# Create a Server Group

---
- name: Create Server Group
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
    - name: Create / Verify a Server Group at CenturyLink Cloud
      clc_group:
        location: 'WA1'
        name: 'Happy Monday'
        parent: 'Default Group'
        state: present
      register: clc

    - name: debug
      debug: var=clc
